FROM nginx:alpine

COPY . /usr/share/nginx/html
RUN find /usr/share/nginx/html -type f \( -name '*.js' -o -name '*.html' \) -exec sed -i 's|http://localhost:4000/api|http://localhost:4001/api|g' {} +
